### ISSUE TITLE
Abstract and author summary section headings garbled

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/JATS-to-Mediawiki#46]
See 
https://en.wikisource.org/w/index.php?title=Wikisource:WikiProject_Open_Access/Programmatic_import_from_PubMed_Central/A_Neural_Circuit_Covarying_with_Social_Hierarchy_in_Macaques&oldid=5034312 .

**Comment by tcatapano** [comment]
Looks like this is caused by the lack of a linebreak preceding the "== Abstract ==" tag.
