### ISSUE TITLE
Missing line breaks

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/JATS-to-Mediawiki#50]
`<p>` and `</p>` tags should be converted into line breaks, but this did not work for
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC4174657 ,
possibly because of the larger problems with whitespace.

For manual corrections, see
https://en.wikisource.org/w/index.php?title=Wikisource%3AWikiProject_Open_Access%2FProgrammatic_import_from_PubMed_Central%2FObituary_Axel_Rethwilm_%281959%E2%80%932014%29&diff=5065055&oldid=5065051

**Comment by tcatapano** [comment]
Think this is fixed. Closing.
