### ISSUE TITLE
boxed text

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/JATS-to-Mediawiki#51]
In 
https://en.wikisource.org/w/index.php?title=Wikisource:WikiProject_Open_Access/Programmatic_import_from_PubMed_Central/Why_Full_Open_Access_Matters&oldid=5225829 ,
the two text boxes from the original article are missing - see
http://dx.doi.org/10.1371/journal.pbio.1001210 .

It seems we are ignoring the "boxed-text" part:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC3226455 .

**Comment by tcatapano** [comment]
What would be the migration path for the boxed-text sections? A section with a heading in the form of "Boxed Text: [Title]" or "Sidebar: [Title]"?

**Comment by Daniel-Mietchen** [comment]
I would like to keep the sections as close to the original, i.e. not add new ones for such boxes. The closest currently existing template is https://en.wikisource.org/wiki/Template:Centered_Box , which is perhaps what we want, so I would go for something like

```
{| class="wikitable"
|-
! Box title
|-
| Text
|}
```
as per https://en.wikisource.org/w/index.php?title=User:Daniel_Mietchen/sandbox&oldid=6149961 .

**Comment by tcatapano** [comment]
Fixed. Closing
