### ISSUE TITLE
<sub> tags inline

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/JATS-to-Mediawiki#59]
See "Na<sub>3</sub>VO<sub>4</sub>"
in 
https://en.wikisource.org/w/index.php?title=Wikisource:WikiProject_Open_Access/Programmatic_import_from_PubMed_Central/Sandbox&oldid=6423276#Western_blotting

**Comment by tcatapano** [comment]
Sub-script now rendering properly. Closing

https://en.wikisource.org/w/index.php?title=Wikisource:WikiProject_Open_Access/Programmatic_import_from_PubMed_Central/Sandbox&oldid=6423276#Western_blotting
